databases:
 -name: postgresql
services:
  -type: web
  name: tech_tales_backend
  env: ruby
  repo: https://github.com/Donvine254/Tech-Tales-Server
  scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 60 
      targetCPUPercent: 60
- type: worker
    name: queue
    runtime: docker
    env: ruby
domains:
      - techtalesapi.render.com
      - techtales-server.render.com
envVars:
      - key: STRIPE_API_KEY
        value: Z2V0IG91dHRhIGhlcmUhCg
      - key: DB_URL
        fromDatabase:
          name: elephant
          property: connectionString
      - key: MINIO_ROOT_PASSWORD
        fromService:
          type: pserv
          name: minio
          envVarKey: MINIO_ROOT_PASSWORD